# Generated by Django 3.2.8 on 2021-11-17 08:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('ing_name',),
            },
        ),
        migrations.CreateModel(
            name='Resipe_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('ingredient_id', models.IntegerField()),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('body_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('categoryFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resepti_app.category')),
                ('recipe_ingFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resepti_app.resipe_ingredient')),
            ],
        ),
    ]
