# Generated by Django 3.2.8 on 2021-11-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resepti_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('ing_name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('ingredient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resepti_app.ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_ingFK',
        ),
        migrations.DeleteModel(
            name='Resipe_Ingredient',
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='recipe_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resepti_app.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='basic_ingredient',
            field=models.ManyToManyField(related_name='recipes', to='resepti_app.Basic_ingredient'),
        ),
    ]
