# Generated by Django 3.2.8 on 2021-10-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resepti_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resepti',
            old_name='category_ID',
            new_name='categoryFK',
        ),
        migrations.RenameField(
            model_name='resepti',
            old_name='ingridient_ID',
            new_name='ingridientFK',
        ),
    ]
