# Generated by Django 3.2.8 on 2021-10-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resepti_app', '0002_auto_20211027_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resepti',
            name='slug',
        ),
    ]
