# Generated by Django 3.2.8 on 2021-11-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resepti_app', '0002_remove_recipe_ingredientfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='resepti_app.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='categoryFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resepti_app.category'),
        ),
        migrations.DeleteModel(
            name='Recipe_Ingredient',
        ),
    ]
