# Generated by Django 3.2.9 on 2021-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepti_app', '0003_auto_20211101_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='resepti_app.Ingredient'),
        ),
    ]
