# Generated by Django 3.2.8 on 2021-11-08 07:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resepti_app', '0004_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='body_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
