# Generated by Django 3.2.8 on 2021-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepti_app', '0005_auto_20211129_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_ingredient',
            name='basicing_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
