# Generated by Django 3.2.8 on 2021-11-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resepti_app', '0006_auto_20211108_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='categoryFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resepti_app.category'),
        ),
    ]
