# Generated by Django 3.2.8 on 2021-11-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepti_app', '0006_alter_basic_ingredient_basicing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='basic_ingredient',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='resepti_app.Basic_ingredient'),
        ),
    ]
