# Generated by Django 3.2.8 on 2021-11-15 11:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resepti_app', '0008_alter_recipe_categoryfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient_quantity',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
