INSERT INTO resepti_app_ingredient (ing_name) VALUES
	 ('omena'),
	 ('papu'),
	 ('pihvi'),
	 ('parsakaali'),
	 ('kaali'),
	 ('porkkana'),
	 ('kana'),
	 ('suklaa'),
	 ('sitruuna'),
	 ('karpalo');
INSERT INTO resepti_app_ingredient (ing_name) VALUES
	 ('ankka'),
	 ('kananmuna'),
	 ('munakoiso'),
	 ('kala'),
	 ('hedelmä'),
	 ('vihreä papu'),
	 ('jauheliha'),
	 ('kinkku'),
	 ('lehtikaali'),
	 ('lammas');
INSERT INTO resepti_app_ingredient (ing_name) VALUES
	 ('salaatti'),
	 ('sitruuna'),
	 ('sieni'),
	 ('pasta'),
	 ('sianliha'),
	 ('peruna'),
	 ('siipikarja'),
	 ('riisi'),
	 ('lohi'),
	 ('simpukka');
INSERT INTO resepti_app_ingredient (ing_name) VALUES
	 ('mereneläviä'),
	 ('äyriäiset'),
	 ('katkarapu'),
	 ('pinaatti'),
	 ('bataatti'),
	 ('tomaatti'),
	 ('kalkkuna'),
	 ('vihannes'),
	 ('kesäkurpitsa'),
	 ('paprika');
INSERT INTO resepti_app_ingredient (ing_name) VALUES
	 ('punajuuri'),
	 ('sipuli'),
	 ('kurkku'),
	 ('maissi'),
	 ('juusto'),
	 ('maito'),
	 ('vehnäjauho'),
	 ('öljy'),
	 ('alkoholi'),
	 ('kerma');